### ISSUE TITLE
Empty dirs and v2.9.1

### ISSUE THREAD

**Issue by drakkan** [goreleaser/nfpm#403]
Hi,

please take a look at the nfpm config [here](https://github.com/drakkan/sftpgo/blob/main/pkgs/build.sh). it works fine with v2.8.0. If I update to v2.9.1 it crashes this way:

```shell
using rpm packager...
DEPRECATION WARNING: 'empty_folders' is deprecated and will be removed in a future version, create content with type 'dir' and directoy name as 'dst' instead
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9169e1]

goroutine 1 [running]:
github.com/goreleaser/nfpm/v2/files.(*Content).Mode(...)
	github.com/goreleaser/nfpm/v2@v2.9.1/files/files.go:126
github.com/goreleaser/nfpm/v2/rpm.asRPMDirectory(0xc000247860)
	github.com/goreleaser/nfpm/v2@v2.9.1/rpm/rpm.go:374 +0x21
github.com/goreleaser/nfpm/v2/rpm.createFilesInsideRPM(0xc0001b0dd0, 0xc0000ac000)
	github.com/goreleaser/nfpm/v2@v2.9.1/rpm/rpm.go:356 +0xbd
github.com/goreleaser/nfpm/v2/rpm.(*RPM).Package(0xc000139500, 0xc0001c5200, {0xaf63c0, 0xc0000bc7c0})
	github.com/goreleaser/nfpm/v2@v2.9.1/rpm/rpm.go:119 +0x1ed
github.com/goreleaser/nfpm/v2/internal/cmd.doPackage({0x7ffd159ffab1, 0x9}, {0x7ffd159ffac9, 0x3}, {0x7ffd159ffac2, 0x3})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/package.go:98 +0x41e
github.com/goreleaser/nfpm/v2/internal/cmd.newPackageCmd.func1(0xc0001b5680, {0xc0000bf080, 0x6, 0x6})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/package.go:31 +0x35
github.com/spf13/cobra.(*Command).execute(0xc0001b5680, {0xc0000bf020, 0x6, 0x6})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b5180)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/goreleaser/nfpm/v2/internal/cmd.(*rootCmd).Execute(0xc00017ff60, {0xc0000c2010, 0xa663a0, 0xc00017ff50})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/root.go:25 +0x5e
github.com/goreleaser/nfpm/v2/internal/cmd.Execute({0xc000164750, 0x405d79}, 0xafec80, {0xc0000c2010, 0x7, 0x7})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/root.go:14 +0x45
main.main()
	github.com/goreleaser/nfpm/v2@v2.9.1/cmd/nfpm/main.go:20 +0x99
using deb packager...
DEPRECATION WARNING: 'empty_folders' is deprecated and will be removed in a future version, create content with type 'dir' and directoy name as 'dst' instead
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x905eac]

goroutine 1 [running]:
github.com/goreleaser/nfpm/v2/deb.createFilesInsideDataTar(0xc0001c3200, 0x90244f, 0x4)
	github.com/goreleaser/nfpm/v2@v2.9.1/deb/deb.go:285 +0x14c
github.com/goreleaser/nfpm/v2/deb.fillDataTar(0xc0000b1098, {0x7f9b4c63d6d8, 0xc0001d3c70})
	github.com/goreleaser/nfpm/v2@v2.9.1/deb/deb.go:247 +0x1e6
github.com/goreleaser/nfpm/v2/deb.createDataTarball(0xc0001c3200)
	github.com/goreleaser/nfpm/v2@v2.9.1/deb/deb.go:226 +0x2bf
github.com/goreleaser/nfpm/v2/deb.(*Deb).Package(0xc0001353e0, 0xc0001c3200, {0xaf63c0, 0xc0000b27c0})
	github.com/goreleaser/nfpm/v2@v2.9.1/deb/deb.go:101 +0x132
github.com/goreleaser/nfpm/v2/internal/cmd.doPackage({0x7ffe0391bab1, 0x9}, {0x7ffe0391bac9, 0x3}, {0x7ffe0391bac2, 0x3})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/package.go:98 +0x41e
github.com/goreleaser/nfpm/v2/internal/cmd.newPackageCmd.func1(0xc0001b3680, {0xc0000b5080, 0x6, 0x6})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/package.go:31 +0x35
github.com/spf13/cobra.(*Command).execute(0xc0001b3680, {0xc0000b5020, 0x6, 0x6})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b3180)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/goreleaser/nfpm/v2/internal/cmd.(*rootCmd).Execute(0xc00017df40, {0xc0000b8010, 0xa663a0, 0xc00017df30})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/root.go:25 +0x5e
github.com/goreleaser/nfpm/v2/internal/cmd.Execute({0xc000160750, 0x405d79}, 0xafec80, {0xc0000b8010, 0x7, 0x7})
	github.com/goreleaser/nfpm/v2@v2.9.1/internal/cmd/root.go:14 +0x45
main.main()
	github.com/goreleaser/nfpm/v2@v2.9.1/cmd/nfpm/main.go:20 +0x99
```

If I use the new way to define empty dirs, for example:

```shell
diff --git a/pkgs/build.sh b/pkgs/build.sh
index c889a42..7376360 100755
--- a/pkgs/build.sh
+++ b/pkgs/build.sh
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-NFPM_VERSION=2.8.0
+NFPM_VERSION=2.9.1
 NFPM_ARCH=${NFPM_ARCH:-amd64}
 if [ -z ${SFTPGO_VERSION} ]
 then
@@ -87,10 +87,11 @@ contents:
     dst: "/etc/sftpgo/sftpgo.json"
     type: "config|noreplace"
 
+  - dst: /srv/sftpgo
+    type: dir
 
-empty_folders:
-  - /var/lib/sftpgo
-  - /srv/sftpgo
+  - dst: /var/lib/sftpgo
+    type: dir
 
 overrides:
   deb:
```

it works but if I open `data.tar.xz` within the deb the empty dirs are not created within the usual `.` directory. Please take a look here

![Schermata del 2021-11-14 10-10-26](https://user-images.githubusercontent.com/553263/141674936-69f073b1-c299-4fde-8730-5e80f178a8ed.png)

I haven't tested the produced deb so I'm not sure if this is a real issue but it is something different from before:

![before](https://user-images.githubusercontent.com/553263/141674996-9669f54c-cb68-4672-9ac5-5a8d8556f0bf.png)

thanks!

**Comment by caarlos0** [comment]
hi, I'm looking into both cases...

on the second one, what does `dpkg-deb -c yourfile.deb` shows?

**Comment by drakkan** [comment]
Here is the requested output, thanks

```shell
$ dpkg-deb -c sftpgo_2.1.3~dev.119-1_amd64.deb 
drwxr-xr-x root/root         0 2021-11-14 10:09 srv/sftpgo
drwxr-xr-x root/root         0 2021-11-14 10:09 var/lib/sftpgo
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./etc/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./etc/sftpgo/
-rw-r--r-- root/root      6298 2021-11-14 10:09 ./etc/sftpgo/sftpgo.json
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./lib/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./lib/systemd/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./lib/systemd/system/
-rw-r--r-- root/root       433 2021-09-19 17:35 ./lib/systemd/system/sftpgo.service
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./srv/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/bin/
-rwxr-xr-x root/root  34704008 2021-11-14 09:54 ./usr/bin/sftpgo
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/bash-completion/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/bash-completion/completions/
-rw-r--r-- root/root      8722 2021-11-14 10:09 ./usr/share/bash-completion/completions/sftpgo
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/man/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/man/man1/
-rw-r--r-- root/root       977 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-completion-bash.1
-rw-r--r-- root/root       724 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-completion-fish.1
-rw-r--r-- root/root       689 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-completion-powershell.1
-rw-r--r-- root/root       895 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-completion-zsh.1
-rw-r--r-- root/root       697 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-completion.1
-rw-r--r-- root/root       567 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen-man.1
-rw-r--r-- root/root       387 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-gen.1
-rw-r--r-- root/root      2040 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-initprovider.1
-rw-r--r-- root/root      5185 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-portable.1
-rw-r--r-- root/root      1662 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-revertprovider.1
-rw-r--r-- root/root      3581 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-serve.1
-rw-r--r-- root/root      1455 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-smtptest.1
-rw-r--r-- root/root      2469 2021-11-14 10:09 ./usr/share/man/man1/sftpgo-startsubsys.1
-rw-r--r-- root/root       564 2021-11-14 10:09 ./usr/share/man/man1/sftpgo.1
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/css/
-rw-r--r-- root/root    170743 2021-09-29 19:19 ./usr/share/sftpgo/static/css/sb-admin-2.min.css
-rw-r--r-- root/root     16958 2021-10-23 19:23 ./usr/share/sftpgo/static/favicon.ico
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/js/
-rw-r--r-- root/root      1265 2021-09-29 19:20 ./usr/share/sftpgo/static/js/sb-admin-2.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/bootstrap/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/bootstrap/js/
-rw-r--r-- root/root     84378 2021-09-29 19:22 ./usr/share/sftpgo/static/vendor/bootstrap/js/bootstrap.bundle.min.js
-rw-r--r-- root/root     63467 2021-09-29 19:22 ./usr/share/sftpgo/static/vendor/bootstrap/js/bootstrap.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/codemirror/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/codemirror/addon/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/codemirror/addon/dialog/
-rw-r--r-- root/root       507 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/dialog/dialog.css
-rw-r--r-- root/root      5250 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/dialog/dialog.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/
-rw-r--r-- root/root      2141 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/jump-to-line.js
-rw-r--r-- root/root      6214 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/match-highlighter.js
-rw-r--r-- root/root       188 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/matchesonscrollbar.css
-rw-r--r-- root/root      3856 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/matchesonscrollbar.js
-rw-r--r-- root/root     11712 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/search.js
-rw-r--r-- root/root     12241 2021-10-08 15:08 ./usr/share/sftpgo/static/vendor/codemirror/addon/search/searchcursor.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/codemirror/addon/selection/
-rw-r--r-- root/root      2507 2021-10-08 13:10 ./usr/share/sftpgo/static/vendor/codemirror/addon/selection/active-line.js
-rw-r--r-- root/root      8709 2021-10-07 18:43 ./usr/share/sftpgo/static/vendor/codemirror/codemirror.css
-rw-r--r-- root/root    399829 2021-10-07 18:43 ./usr/share/sftpgo/static/vendor/codemirror/codemirror.js
-rw-r--r-- root/root     15924 2021-09-29 17:56 ./usr/share/sftpgo/static/vendor/codemirror/meta.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/datatables/
-rw-r--r-- root/root      4869 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/buttons.bootstrap4.min.css
-rw-r--r-- root/root      1383 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/buttons.bootstrap4.min.js
-rw-r--r-- root/root      7275 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.bootstrap4.min.css
-rw-r--r-- root/root      4520 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.bootstrap4.min.js
-rw-r--r-- root/root     24315 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.buttons.min.js
-rw-r--r-- root/root       568 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.checkboxes.css
-rw-r--r-- root/root     14087 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.checkboxes.min.js
-rw-r--r-- root/root     14380 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.fixedHeader.min.js
-rw-r--r-- root/root     16849 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.responsive.min.js
-rw-r--r-- root/root     12663 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/dataTables.select.min.js
-rw-r--r-- root/root      2755 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/ellipsis.js
-rw-r--r-- root/root       265 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/fixedHeader.bootstrap4.min.css
-rw-r--r-- root/root     87897 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/jquery.dataTables.min.js
-rw-r--r-- root/root      4301 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/responsive.bootstrap4.min.css
-rw-r--r-- root/root      3661 2021-09-29 20:09 ./usr/share/sftpgo/static/vendor/datatables/responsive.bootstrap4.min.js
-rw-r--r-- root/root      4431 2021-09-29 20:03 ./usr/share/sftpgo/static/vendor/datatables/select.bootstrap4.min.css
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/fontawesome-free/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/fontawesome-free/css/
-rw-r--r-- root/root     57912 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/css/fontawesome.min.css
-rw-r--r-- root/root       677 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/css/regular.min.css
-rw-r--r-- root/root       669 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/css/solid.min.css
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/
-rw-r--r-- root/root     34034 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-regular-400.eot
-rw-r--r-- root/root    144714 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-regular-400.svg
-rw-r--r-- root/root     33736 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-regular-400.ttf
-rw-r--r-- root/root     16276 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-regular-400.woff
-rw-r--r-- root/root     13276 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-regular-400.woff2
-rw-r--r-- root/root    203030 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-solid-900.eot
-rw-r--r-- root/root    918991 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-solid-900.svg
-rw-r--r-- root/root    202744 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-solid-900.ttf
-rw-r--r-- root/root    101652 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-solid-900.woff
-rw-r--r-- root/root     78196 2021-03-16 14:15 ./usr/share/sftpgo/static/vendor/fontawesome-free/webfonts/fa-solid-900.woff2
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/fonts/
-rw-r--r-- root/root     11560 2019-11-13 08:37 ./usr/share/sftpgo/static/vendor/fonts/LICENSE.txt
-rw-r--r-- root/root       134 2019-11-13 08:37 ./usr/share/sftpgo/static/vendor/fonts/README.txt
-rw-r--r-- root/root     82564 2019-11-13 08:37 ./usr/share/sftpgo/static/vendor/fonts/Roboto-Bold-webfont.woff
-rw-r--r-- root/root     81348 2019-11-13 08:37 ./usr/share/sftpgo/static/vendor/fonts/Roboto-Light-webfont.woff
-rw-r--r-- root/root     80304 2019-11-13 08:37 ./usr/share/sftpgo/static/vendor/fonts/Roboto-Regular-webfont.woff
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/jquery-easing/
-rw-r--r-- root/root      1656 2019-03-18 07:05 ./usr/share/sftpgo/static/vendor/jquery-easing/jquery.easing.compatibility.js
-rw-r--r-- root/root      2302 2019-03-18 07:05 ./usr/share/sftpgo/static/vendor/jquery-easing/jquery.easing.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/jquery/
-rw-r--r-- root/root     89501 2021-04-10 08:39 ./usr/share/sftpgo/static/vendor/jquery/jquery.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/moment/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/moment/js/
-rw-r--r-- root/root     58862 2020-11-22 12:02 ./usr/share/sftpgo/static/vendor/moment/js/moment.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/tempusdominus/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/tempusdominus/css/
-rw-r--r-- root/root     11963 2021-02-07 21:56 ./usr/share/sftpgo/static/vendor/tempusdominus/css/tempusdominus-bootstrap-4.min.css
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/static/vendor/tempusdominus/js/
-rw-r--r-- root/root     61588 2021-02-07 21:56 ./usr/share/sftpgo/static/vendor/tempusdominus/js/tempusdominus-bootstrap-4.min.js
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/templates/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/templates/common/
-rw-r--r-- root/root      4655 2021-11-13 13:01 ./usr/share/sftpgo/templates/common/forgot-password.html
-rw-r--r-- root/root      4907 2021-11-13 13:01 ./usr/share/sftpgo/templates/common/reset-password.html
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/templates/email/
-rw-r--r-- root/root       183 2021-11-13 13:01 ./usr/share/sftpgo/templates/email/reset-password.html
-rw-r--r-- root/root       605 2021-10-03 14:10 ./usr/share/sftpgo/templates/email/retention-check-report.html
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/templates/webadmin/
-rw-r--r-- root/root      6009 2021-09-27 15:05 ./usr/share/sftpgo/templates/webadmin/admin.html
-rw-r--r-- root/root      7615 2021-10-08 10:02 ./usr/share/sftpgo/templates/webadmin/admins.html
-rw-r--r-- root/root      5208 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/adminsetup.html
-rw-r--r-- root/root     10823 2021-10-24 18:19 ./usr/share/sftpgo/templates/webadmin/base.html
-rw-r--r-- root/root      3162 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/baselogin.html
-rw-r--r-- root/root      1781 2021-09-27 17:22 ./usr/share/sftpgo/templates/webadmin/changepassword.html
-rw-r--r-- root/root      6869 2021-11-02 19:32 ./usr/share/sftpgo/templates/webadmin/connections.html
-rw-r--r-- root/root      8065 2021-10-08 10:02 ./usr/share/sftpgo/templates/webadmin/defender.html
-rw-r--r-- root/root      6212 2021-07-16 18:35 ./usr/share/sftpgo/templates/webadmin/folder.html
-rw-r--r-- root/root     11173 2021-11-06 13:42 ./usr/share/sftpgo/templates/webadmin/folders.html
-rw-r--r-- root/root     21386 2021-11-13 14:55 ./usr/share/sftpgo/templates/webadmin/fsconfig.html
-rw-r--r-- root/root      2519 2021-11-13 13:01 ./usr/share/sftpgo/templates/webadmin/login.html
-rw-r--r-- root/root      2664 2021-02-02 19:40 ./usr/share/sftpgo/templates/webadmin/maintenance.html
-rw-r--r-- root/root      1835 2021-09-29 20:40 ./usr/share/sftpgo/templates/webadmin/message.html
-rw-r--r-- root/root     15830 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/mfa.html
-rw-r--r-- root/root      2272 2021-09-27 19:52 ./usr/share/sftpgo/templates/webadmin/profile.html
-rw-r--r-- root/root      5031 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/status.html
-rw-r--r-- root/root      1778 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/twofactor-recovery.html
-rw-r--r-- root/root      2124 2021-09-04 12:25 ./usr/share/sftpgo/templates/webadmin/twofactor.html
-rw-r--r-- root/root     46358 2021-11-05 12:04 ./usr/share/sftpgo/templates/webadmin/user.html
-rw-r--r-- root/root     12328 2021-10-08 10:02 ./usr/share/sftpgo/templates/webadmin/users.html
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./usr/share/sftpgo/templates/webclient/
-rw-r--r-- root/root      9088 2021-11-06 13:42 ./usr/share/sftpgo/templates/webclient/base.html
-rw-r--r-- root/root      3382 2021-09-04 12:25 ./usr/share/sftpgo/templates/webclient/baselogin.html
-rw-r--r-- root/root      1780 2021-09-27 19:41 ./usr/share/sftpgo/templates/webclient/changepassword.html
-rw-r--r-- root/root      6604 2021-11-06 13:42 ./usr/share/sftpgo/templates/webclient/editfile.html
-rw-r--r-- root/root     27169 2021-11-06 13:42 ./usr/share/sftpgo/templates/webclient/files.html
-rw-r--r-- root/root      2306 2021-11-13 13:01 ./usr/share/sftpgo/templates/webclient/login.html
-rw-r--r-- root/root      1834 2021-05-01 12:30 ./usr/share/sftpgo/templates/webclient/message.html
-rw-r--r-- root/root     19328 2021-09-04 12:25 ./usr/share/sftpgo/templates/webclient/mfa.html
-rw-r--r-- root/root      6224 2021-09-28 11:12 ./usr/share/sftpgo/templates/webclient/profile.html
-rw-r--r-- root/root     10163 2021-11-06 13:42 ./usr/share/sftpgo/templates/webclient/share.html
-rw-r--r-- root/root     10015 2021-11-06 13:42 ./usr/share/sftpgo/templates/webclient/shares.html
-rw-r--r-- root/root      1566 2021-09-04 12:25 ./usr/share/sftpgo/templates/webclient/twofactor-recovery.html
-rw-r--r-- root/root      1912 2021-09-04 12:25 ./usr/share/sftpgo/templates/webclient/twofactor.html
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./var/
drwxr-xr-x 0/0               0 2021-11-14 10:09 ./var/lib/
```

**Comment by caarlos0** [comment]
as you can see, the files are there:

```
$ dpkg-deb -c sftpgo_2.1.3~dev.119-1_amd64.deb 
drwxr-xr-x root/root         0 2021-11-14 10:09 srv/sftpgo
drwxr-xr-x root/root         0 2021-11-14 10:09 var/lib/sftpgo
```

they are not prefixed with `./` though, which shouldn't be a problem, but just fixed it on 175e175 anyway

**Comment by drakkan** [comment]
great, thank you for the quick fix

**Comment by caarlos0** [comment]
will release .2 soon :) thanks for reporting!
